name = "pchip"
version = "1.1.0"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2019-2024, Jacob Williams"
license = "BSD-3"
description = "Piecewise Cubic Hermite Interpolation Package"
homepage = "https://github.com/jacobwilliams/PCHIP"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = true
