dpchdf – PCHIP
dpchdf Function
26 statements
Source File
private function dpchdf(k, x, s, ierr) result(deriv)
Computes divided differences for dpchce and dpchsp
Uses a divided difference formulation to compute a K-point approximation to the derivative at X(K) based on the data in X and S.
Called by dpchce and dpchsp to compute 3- and 4-point boundary derivative approximations.
References
Carl de Boor, A Practical Guide to Splines, Springer-Verlag, New York, 1978, pp. 10-16.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
is the order of the desired derivative approximation. K must be at least 3 (error return if not).
real(kind=wp), intent(in) :: x(k)
contains the K values of the independent variable. X need not be ordered, but the values MUST be distinct. (Not checked here.)
real(kind=wp), intent(inout) :: s(k)
contains the associated slope values: S(I) = (F(I+1)-F(I))/(X(I+1)-X(I)), I=1(1)K-1. (Note that S need only be of length K-1.) Will be destroyed on output.
integer, intent(out) :: ierr
will be set to -1 if K<2 .
Return Value real(kind=wp)
will be set to the desired derivative approximation if IERR=0 or to zero if IERR=-1.
Calls
Called by
Source Code
    function dpchdf (k, x, s, ierr) result(deriv)
    integer,intent(in)     :: k    !! is the order of the desired derivative approximation.
                                   !! K must be at least 3 (error return if not).
    real(wp),intent(in)    :: x(k) !! contains the K values of the independent variable.
                                   !! X need not be ordered, but the values **MUST** be
                                   !! distinct.  (Not checked here.)
    real(wp),intent(inout) :: s(k) !! contains the associated slope values:
                                   !! `S(I) = (F(I+1)-F(I))/(X(I+1)-X(I)), I=1(1)K-1`.
                                   !! (Note that S need only be of length K-1.)
                                   !! Will be destroyed on output.
    integer,intent(out)    :: ierr !! will be set to -1 if K<2 .
    real(wp) :: deriv  !! will be set to the desired derivative approximation if
                       !! IERR=0 or to zero if IERR=-1.
    integer :: i, j
    real(wp) :: value
    ! check for legal value of k.
    if (k < 3) then
        ierr = -1
        call xermsg ('PCHIP', 'dpchdf', 'k less than three', ierr, 1)
        deriv = zero
    else
        ! compute coefficients of interpolating polynomial.
        do j = 2, k-1
            do  i = 1, k-j
                s(i) = (s(i+1)-s(i))/(x(i+j)-x(i))
            end do
        end do
        ! evaluate derivative at x(k).
        value = s(1)
        do i = 2, k-1
            value = s(i) + value*(x(k)-x(i))
        end do
        ! normal return.
        ierr = 0
        deriv = value
    end if
    end function dpchdf
Call graph
dpchdf calls xermsg
dpchce calls dpchdf
dpchsp calls dpchdf
dpchic calls dpchce