xermsg – PCHIP
xermsg Subroutine
9 statements
Source File
private subroutine xermsg(librar, subrou, messg, nerr, level)
Error reporter.
A very simplified version of the SLATEC routine.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: librar
name of the library
character(len=*), intent(in) :: subrou
name of the routine that detected the error
character(len=*), intent(in) :: messg
text of the error or warning message
integer, intent(in) :: nerr
error code
integer, intent(in) :: level
value in the range 0 to 2 that indicates the level (severity) of the error.
Called by
Contents
Source Code
xermsg
Source Code
    subroutine xermsg(librar,subrou,messg,nerr,level)
    implicit none
    character(len=*),intent(in) :: librar !! name of the library
    character(len=*),intent(in) :: subrou !! name of the routine that detected the error
    character(len=*),intent(in) :: messg  !! text of the error or warning message
    integer,intent(in)          :: nerr   !! error code
    integer,intent(in)          :: level  !! value in the range 0 to 2 that indicates the
                                          !! level (severity) of the error.
    write(error_unit, '(A,I2,A)') 'Error ',nerr,' in '//trim(librar)//&
                                  ' : '//trim(subrou)//' : '//trim(messg)
    end subroutine xermsg
Call graph
dchfdv calls xermsg
dpchce calls xermsg, dpchdf
dpchcm calls xermsg
dpchim calls xermsg
dchfev calls xermsg
dpchfd calls xermsg, dchfdv
dpchbs calls xermsg
dpchid calls xermsg
dpchfe calls xermsg, dchfev
dpchsp calls xermsg, dpchdf
dpchdf calls xermsg
dpchsw calls xermsg
dpchia calls xermsg, dpchid
dpchic calls xermsg, dpchce, dpchcs
dpchcs calls dpchsw